package pit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.Map;
import javax.jms.*;
import javax.naming.*;

/*
 * This is the ONLY file that you are to edit.  It is the model of play for
 * every PITplayer.  Each PITplayer instantiates this model and uses it to
 * process the messages it receives.
 */
public class PITPlayerModel {

    // Each PITplayer has a unique myPlayerNumber.  It is set in the PITPlayer constructor.
    private int myPlayerNumber;
    // Cards is this player's set of cards.  
    private final ArrayList cards = new ArrayList();
    // tradeCount counts trades.
    private int tradeCount = 0;
    // maxTrades is the maximum number of trades, after which trading is stopped.
    private final int maxTrades = 20000;
    // numPlayers are the number of Players trading.  This comes with a NewHand from the PITsnapshot servlet
    private int numPlayers = 0;
    // a flag to indicate if the snapshot started
    private boolean snapShotStarted = false;
    // A set to store incoming channels where we have seen a Marker
    private Set<Integer> stopList = new HashSet<>();

    /* The snapshot servlet (PITsnapshot) is expecting to be passed an ObjectMessage
     * where the object is a HashMap. Therefore this definition of that HashMap is 
     * provided although it is not currently used (it is for you to use).
     * PITsnapshot is expecting a set of attibute/value pairs.  These include the player
     * number, as in state.put("Player", myPlayerNumber), and each commodity string
     * and the number of that commodity in the snapshot.
     * Also included below is a utility method that will turn a HashMap into a string
     * which is useful for printing diagnostic messages to the console.
     */
    private HashMap<String, Integer> state = new HashMap();

    // PITPlayerModel constructor saves what number player this object represents.
    PITPlayerModel(int myNumber) {
        myPlayerNumber = myNumber;
    }

    public void onMessage(Message message) {
        try {
            if (message instanceof ObjectMessage) {
                Object o = ((ObjectMessage) message).getObject();

                // There are 4 types of messages:  Reset, NewHand, Trade, and Marker
                // Reset the Player.  The Reset message is generated by the PITsnapshot servlet
                if (o instanceof Reset) {
                    doReset((Reset) o);

                    // NewHand received from PITsnapshot
                } else if (o instanceof NewHand) {
                    // Add the new hand into cards
                    doNewHand((NewHand) o);
                    // Trade away a card
                    doMakeTrade();
                    // Receive a Trade from another Player
                } else if (o instanceof Trade) {
                    // Haven't received Marker from this channel, add the card into state
                    int source = ((Trade) o).sourcePlayer;
                    doAddTrade((Trade) o);
                    // From a new channel
                    if (!stopList.contains(source)) {
                        // Snapshot have started
                        if (snapShotStarted) {
                            String type = ((Trade) o).tradeCard;
                            if (state.containsKey(type)) {
                                int num = state.get(type);
                                state.put(type, ++num);
                            } else {
                                state.put(type, 1);
                            }
                        } 
                    }
                    // Trade away a card
                    doMakeTrade();
                } else if (o instanceof Marker) {
                    // Take 
                    doMarker((Marker) o);
                } else {
                    System.out.println("PITplayer" + myPlayerNumber + " received unknown Message type");
                    // just ignore it
                }
            }
        } catch (Exception e) {
            System.out.println("Exception thrown in PITplayer" + myPlayerNumber + ": " + e.getMessage());
        }
    }

    private void doMarker(Marker marker) throws JMSException, Exception {
        /* Currently not participating */
        int source = marker.source;
        if (source != -1) {
            stopList.add(source);
        }
        // Begin snapshot, count # of each commodity in hand only
        if (!snapShotStarted) {
            for (Object card : cards) {
                String card1 = (String) card;
                if (state.containsKey(card1)) {
                    int num = state.get(card1);
                    state.put(card1, ++num);
                } else {
                    state.put(card1, 1);
                }
            }
            // Send Marker on every outgoing channel
            for (int sendTo = 0; sendTo < numPlayers; sendTo++) {
                if (sendTo == myPlayerNumber) {
                    continue;
                }
                String sendToJNDI = "jms/PITplayer" + sendTo;
                sendToQueue(sendToJNDI, new Marker(myPlayerNumber));
            }
            snapShotStarted = true;
        }
        // Having received Markers from all other channels
        if (stopList.size() == numPlayers - 1) {
            state.put("Player", myPlayerNumber);
            //Send snapshot
            sendToQueue("jms/PITsnapshot", state);
            // Clear all variables
            state.clear();
            stopList.clear();
            snapShotStarted = false;
        }
    }

//    private void sendMarker(Marker marker) throws JMSException, Exception {
//        
//    }
    private void doReset(Reset reset) throws JMSException, Exception {
        System.out.println("PITplayer" + myPlayerNumber + " received reset");
        // Drop all cards in hand
        cards.clear();
        tradeCount = 0;
        numPlayers = 0;
        // Reply to the PITsnapshot servlet acknowledging the Reset
        sendToQueue("jms/PITmonitor", reset);
    }

    private void doNewHand(NewHand hand) throws JMSException {
        // Add new hand cards.  
        // It is actually possible that a trade had added a card already.
        cards.addAll((hand).handCard);
        numPlayers = (hand).numPlayers;
        System.out.println("PITplayer" + myPlayerNumber + " new hand: " + toString(cards));
    }

    private void doAddTrade(Trade trade) throws JMSException {
        // Having received a Trade card from another Player, add it to my hand of cards
        cards.add(trade.tradeCard);

        System.out.println("PITplayer" + myPlayerNumber + " received: " + trade.tradeCard + " from player: " + trade.sourcePlayer);
        System.out.println("PITplayer" + myPlayerNumber + " hand: " + toString(cards));
    }

    private void doMakeTrade() throws JMSException, Exception {

        // if hit maxTrades limit, then stop sending trades
        if (maxTrades(maxTrades)) {
            return;
        }

        /*
         * If numPlayers == 0, while we have received a Trade, we have not 
         * received our NewHand yet, so we don't know how many players there 
         * are.  Therefore, don't send out a Trade at this time.
         * 
         */
        if (numPlayers == 0) {
            return;
        }

        // Create a new Trade from my set of cards, and send to another player
        Trade newTrade = new Trade();
        newTrade.tradeCard = (String) cards.remove(0);
        newTrade.sourcePlayer = myPlayerNumber;

        // Find a random player to trade to (not including myself)
        int sendTo = myPlayerNumber;
        while (sendTo == myPlayerNumber) {
            sendTo = Math.round((float) Math.random() * (numPlayers - 1));
        }

        //Send the card to the other player
        System.out.println("PITplayer" + myPlayerNumber + " sending: " + newTrade.tradeCard + " to player: " + sendTo);
        String sendToJNDI = "jms/PITplayer" + sendTo;
        sendToQueue(sendToJNDI, newTrade);
    }

    // Create a string of hand size and all cards for use in printing
    private String toString(ArrayList hand) {

        String cardsString = "size: " + hand.size() + " ";
        for (int i = 0; i < hand.size(); i++) {
            cardsString += hand.get(i) + " ";
        }
        return cardsString;
    }

    // Create a printable version of the "state".
    private String toString(HashMap<String, Integer> state) {
        String stateString = "";
        for (Iterator it = state.entrySet().iterator(); it.hasNext();) {
            Map.Entry entry = (Map.Entry) it.next();
            String commodity = (String) entry.getKey();
            int number = ((Integer) entry.getValue()).intValue();
            stateString += "{" + commodity + ":" + number + "} ";
        }
        return stateString;
    }

    // Send an object to a Queue, given its JNDI name
    private void sendToQueue(String queueJNDI, Serializable message) throws Exception {
        // Gather necessary JMS resources
        Context ctxt = new InitialContext();
        Connection con = ((ConnectionFactory) ctxt.lookup("jms/myConnectionFactory")).createConnection();
        Session session = con.createSession(false, Session.AUTO_ACKNOWLEDGE);
        Queue q = (Queue) ctxt.lookup(queueJNDI);
        MessageProducer writer = session.createProducer(q);
        ObjectMessage msg = session.createObjectMessage(message);
        // Send the object to the Queue
        writer.send(msg);
        session.close();
        con.close();
        ctxt.close();
    }

    // Stop trading when the max number of Trades is reached
    private boolean maxTrades(int max) {
        if ((tradeCount % 100) == 0) {
            System.out.println("PITplayer" + myPlayerNumber + " tradeCount: " + tradeCount);
        }
        return (tradeCount++ < max) ? false : true;
    }
}
